### ISSUE TITLE
Automatic controllers registration doesn't work with Apitte

### ISSUE THREAD

**Issue by pytelCZ** [contributte/di#27]
after upgrade from 0.5.1 to 0.5.2 / 0.5.3 automatic controllers registration doesn't work for Apitte api controllers....
using standard [example](https://github.com/contributte/apitte/blob/master/.docs/endpoints.md#automatic-controllers-registration)

**Comment by f3l1x** [comment]
Hi, thanks. I will take a look as soon as possible.

**Comment by f3l1x** [comment]
I'm testing https://github.com/contributte/apitte-skeleton/ and it works. Can you specify what is not working for you?

**Comment by pytelCZ** [comment]
Don't know where the problem is. With 0.5.1 call to API works OK, after upgrade it throws this [error](http://cube-in.cz/nette/chyba.html)

**Comment by f3l1x** [comment]
Can you share project with me?

**Comment by pytelCZ** [comment]
Unfortunately, this is a large project, the whole send is not possible.
But I can send the API + configuration part (without DB connection and so on).
Send me your email to kubin@cube-in.cz

**Comment by f3l1x** [comment]
I've sent the email. Do you get it?

**Comment by pytelCZ** [comment]
yes, I'm on holiday this week, I'll send next week on Wednesday

**Comment by f3l1x** [comment]
@pytelCZ That's silly. I've just discovered what's wrong.

```neon
extensions:
	resource: Contributte\DI\Extension\ResourceExtension
	api: Apitte\Core\DI\ApiExtension
```

It's really needed you have to register resource extension before apitte. It's because resource extension lookup for classes a apitte use that classes.

**Comment by pytelCZ** [comment]
works perfect, thank you
