### ISSUE TITLE
Call to undefined method Nette\Loaders\RobotLoader::setCacheStorage()

### ISSUE THREAD

**Issue by suplere** [contributte/di#6]
Hello,

I testing apitte but when I use this in config.neon: 
**resource:
    resources:
            App\Controllers\:
                paths: [%appDir%/controllers]**

I get this error:
Nette\MemberAccessException
Call to undefined method Nette\Loaders\RobotLoader::setCacheStorage().

Last muted error
Warning: file_get_contents(/var/www/api_nette/app/../temp/cache/Nette.Configurator/Container_5efa733610.php.meta): failed to open stream: No such file or directory

.../vendor/nette/di/src/DI/ContainerLoader.php:108

If I define controller in service all works fine.

**Comment by f3l1x** [comment]
Hi, thanks for reporting. Could you provide more info? Composer.jsonat first?

**Comment by f3l1x** [comment]
Well, I think I got it.

You're running robot-loader >= 3.0.0 (https://github.com/nette/robot-loader/releases/tag/v3.0.0). There's no setCacheStorage method.

I will fix it.

**Comment by f3l1x** [comment]
Fixed.
